name: 'Deploy website'
on:
  workflow_dispatch:
    inputs:
      just-deploy:
        description: 'Just deploy (overrides skip)'
        type: 'boolean'
        required: true
        default: false
      skip-deploy:
        description: 'Skip deploy'
        type: 'boolean'
        required: true
        default: false
  push:
    branches:
      - 'main'
    paths:
      - 'Guides/**'
      - 'ExtraInfo/**'
  pull_request:
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']
    branches:
      - 'main'
    paths:
      - 'Guides/**'
      - 'ExtraInfo/**'
jobs:
  generate:
    name: 'Generate chip markdown'
    runs-on: 'ubuntu-latest'
    if: ${{ !inputs.just-deploy || (github.event_name == 'pull_request' && !github.event.pull_request.draft) }}
    permissions:
      contents: 'write'
    outputs:
      commit-sha: '${{ steps.commit-push.outputs.commit-sha }}'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          repository: '${{ github.event.pull_request.head.repo.full_name || github.repository }}'
          ref: '${{ github.event.pull_request.head.sha || github.sha }}'
      - name: 'Setup Node'
        uses: 'actions/setup-node@v3'
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './Source'
      - name: 'Run script'
        working-directory: './Source'
        run: |
          npm ci
          npm run generate
      - name: 'Commit and push'
        id: 'commit-push'
        #continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "actions-user"
          git add Circuits/docs
          git commit -m "Generated markdown and svg - based on ${{ github.sha }}"
          git push
          echo "commit-sha=$(git log --format='%H' -1)" >> "$GITHUB_OUTPUT"
  deploy:
    name: 'Deploy (Production)'
    runs-on: 'ubuntu-latest'
    needs: 'generate'
    if: ${{ !failure() && github.event_name != 'pull_request' && (!inputs.skip-deploy || inputs.just-deploy) }}
    permissions:
      contents: 'read'
      deployments: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          ref: '${{ needs.generate.outputs.commit-sha || github.sha }}'
      - name: 'Setup Node'
        uses: 'actions/setup-node@v3'
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './Circuits'
      - name: 'Build'
        working-directory: './Circuits'
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm ci
          npm run build
      - name: 'Deploy to Cloudflare Pages'
        uses: 'cloudflare/pages-action@v1.5.0'
        with:
          apiToken: '${{ secrets.CLD_FLR_TKN }}'
          accountId: '${{ secrets.CLD_FLR_ID }}'
          projectName: 'circuits'
          branch: 'main'
          directory: './build'
          workingDirectory: './Circuits'
          gitHubToken: '${{ secrets.GITHUB_TOKEN }}'
  test-deploy:
    name: 'Deploy (Preview)'
    runs-on: 'ubuntu-latest'
    needs: 'generate'
    if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.draft }}
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          repository: '${{ github.event.pull_request.head.repo.full_name }}'
          ref: '${{ needs.generate.outputs.commit-sha }}'
      - name: 'Setup Node'
        uses: 'actions/setup-node@v3'
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './Circuits'
      - name: 'Build'
        working-directory: './Circuits'
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm ci
          npm run build
      - name: 'Deploy to Cloudflare Pages'
        uses: 'cloudflare/pages-action@v1.5.0'
        with:
          apiToken: '${{ secrets.CLD_FLR_TKN }}'
          accountId: '${{ secrets.CLD_FLR_ID }}'
          projectName: 'circuits'
          #branch: '' ill figure something out to make unique branches for pull requests
          directory: './build'
          workingDirectory: './Circuits'
